spring:
  application:
    name: authserver
  datasource: # mysql
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}