spring:
  application:
    name: authserver
  config:
    import: "application-oauth.yml"
  datasource: # mysql
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa: # jpa settings
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: false
  data:
    redis: # Redis
      timeout: 500ms
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      userTTL: ${USER_TTL}
      jwtTTL: ${JWT_TTL}
  kafka: # Kafka
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable-idempotence: true
        max-in-flight-requests-per-connection: 1
        retries: 5
        delivery-timeout-ms: 120000

jwt: #JWT
  secret: ${JWT_SECRET}
  time:
    accessTokenExpireTime: ${JWT_ACCESS_TIME}
    refreshTokenExpireTime: ${JWT_REFRESH_TIME}

gcp: #GCP
  project-id: ${GCP_PROJECT_ID}
  bucket-name: ${BUCKET_NAME}
  credentials: ${SERVICE_CREDENTIALS}
  user-image: ${USER_IMAGE}
  company-image: ${COMPANY_IMAGE}