spring:
  application:
    name: authserver
  config:
    import: "application-oauth.yml"
  datasource: # mysql
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa: # jpa settings
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: false
  data:
    redis:
      timeout: 500ms
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      userTTL: ${USER_TTL}
      jwtTTL: ${JWT_TTL}

jwt:
  secret: ${JWT_SECRET}
  time:
    accessTokenExpireTime: ${JWT_ACCESS_TIME}
    refreshTokenExpireTime: ${JWT_REFRESH_TIME}

gcp:
  project-id: ${GCP_PROJECT_ID}
  bucket-name: ${BUCKET_NAME}
  credentials: ${SERVICE_CREDENTIALS}
  user-image: ${USER_IMAGE}
  company-image: ${COMPANY_IMAGE}

logging:
  level:
    web: info
    org:
      springframework:
        security:
          web:
            FilterChainProxy: info