spring:
  application:
    name: authserver
  datasource: # mysql
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: "application-oauth.yml"

jwt:
  secret: ${JWT_SECRET}