spring:
  application:
    name: authserver
  config:
    import: "application-oauth.yml"
  datasource: # mysql
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa: # jpa settings
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: false
  data:
    redis:
      timeout: 500ms
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  time:
    accessTokenExpireTime: ${JWT_ACCESS_TIME}
    refreshTokenExpireTime: ${JWT_REFRESH_TIME}

logging:
  level:
    web: info
    org:
      springframework:
        security:
          web:
            FilterChainProxy: info